Bundle 'tpope/vim-classpath'
Bundle 'tpope/vim-dispatch'
Bundle 'guns/vim-clojure-static'
Bundle 'tpope/vim-fireplace'
Bundle 'tpope/vim-leiningen'
Bundle 'paredit.vim'
Bundle 'kien/rainbow_parentheses.vim'
